bankproject/bankapp/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('',views.index,name="home"),
    path('branches/', views.branches, name="branches"),
    path('booking/', views.booking, name="booking"),
    path('department/', views.department, name="departments"),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bankapp.urls')),
    path('credentials/', include('credentials.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bankproject/credentials/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

bankproject/bankapp/models.py
from django.contrib.gis.geoip2.resources import Country, City
from django.db import models


# Create your models here.
class Departments(models.Model):
    dep_name = models.CharField(max_length=100)
    dep_description = models.TextField()

    def __str__(self):
        return self.dep_name

#
# class District(models.Model):
#     dic_name = models.CharField(max_length=255)
#
#     def __str__(self):
#         return self.dic_name
#
#
# class Branchname(models.Model):
#     branch_name = models.CharField(max_length=255)
#     dic_name = models.ForeignKey(District, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.branch_name


class Account_type(models.Model):
    ac_type = models.CharField(max_length=255)

    def __str__(self):
        return self.ac_type


class Country(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


Type_Select = (('male', "MALE"),
               ('female', "FEMALE"),
               ('not specified', 'NOT SPECIFIED')
               )
Gender = models.CharField(max_length=10, choices=Type_Select)

class Booking(models.Model):
    u_name = models.CharField(max_length=255)
    date_birth = models.DateField()
    age = models.IntegerField()
    Gender = models.CharField(max_length=100,choices=Type_Select)
    u_phone = models.CharField(max_length=10)
    u_email = models.EmailField()
    u_address = models.TextField(max_length=1000)
    # dic_name = models.ForeignKey(District, on_delete=models.CASCADE)
    # branch_name = models.ForeignKey(Branchname, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    ac_type = models.ForeignKey(Account_type, on_delete=models.CASCADE)
    booking_date = models.DateField()
    booked_on = models.DateField(auto_now=True)
    DEBIT_CARD = models.BooleanField()
    CREDIT_CARD = models.BooleanField()
    CHEQUE_BOOK = models.BooleanField()

bankproject/credentials/models.py
from django.db import models

# Create your models here.

bankproject/bankapp/forms.py
from django import forms
from .models import Booking, City


class DateInput(forms.DateInput):
    input_type = 'date'


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = "__all__"

        widgets = {
            'booking_date': DateInput(),
            'date_birth': DateInput(),
            'Gender': forms.RadioSelect(),

        }
        labels = {
            'date_birth': "DATE OF BIRTH",
            'u_name': "USERNAME",
            'age': "AGE",
            'Gender': "GENDER",
            'u_phone': "CONTACT NUMBER",
            'u_email': "EMAIL ADDRESS",
            'u_address': "HOME ADDRESS",
            # 'dic_name': "DISTRICT",
            # 'branch_name': 'BRANCH',
            'country': "DISTRICT",
            'city': 'BRANCH',
            'ac_type': 'ACCOUNT TYPE',
            'booking_date': 'DATE OF BOOKING',


        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

bankproject/bankapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from flask import redirect

from .models import Departments, City, Booking
from .forms import BookingForm


# Create your views here.
def index(request):
    return render(request, "index.html")


def branches(request):
    return render(request, "branches.html")


def booking(request):
    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'confirmation.html')

    form = BookingForm()
    dict_form = {
        'form': form
    }
    return render(request, "booking.html", dict_form)



def department(request):
    dict_dept = {
        'dept': Departments.objects.all()
    }
    return render(request, "departments.html", dict_dept)



# def person_create_view(request):
#     form = BookingForm()
#     if request.method == 'POST':
#         form = BookingForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('booking')
#     return render(request, 'booking.html', {'form': form})



def person_update_view(request, pk):
    person = get_object_or_404(Booking, pk=pk)
    form = BookingForm(instance=booking)
    if request.method == 'POST':
        form = BookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'booking.html', {'form': form})


# AJAX
def load_cities(request):
    country_id = request.GET.get('country_id')
    cities = City.objects.filter(country_id=country_id).all()
    return render(request, 'dropdown.html', {'cities': cities})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

bankproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('booking')
        else:
            messages.info(request, "Invalid credentials")
            return redirect('login')
    return render(request, "login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already exist!!!")
                return redirect("register")
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save();
            return redirect('login')
        else:
            messages.info(request, "Password doesn't match!!!")
            return redirect("register")
        return redirect('/')

    return render(request, "register.html")


def logout(request):
    auth.logout(request)
    messages.info(request, "You are logged out!!!")
    return redirect("login")

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet"
      href=" https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css ">
    <link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
      <link rel="icon" href="{% static 'imgs/logo.png' %}" alt="Logo"  style="width:200px;height=20px">

  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary shadow-sm p-3 mb-5" >
          <div  class="container-fluid">

                <a  class="navbar-brand" href="{% url 'home' %}">

                    <img src="{% static 'imgs/logo.png' %}">

                </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                  </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul id="menubar" class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item ">
                      <a  id="menu1" class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle nav-link active text-white" aria-current="page" href="{% url 'branches' %}" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        BRANCHES
                      </a>
                      <ul class="dropdown-menu dropdown-menu-primary" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram" target="_blank">TRIVANDRUM</a></li>
                        <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam" target="_blank">KOTTAYAM</a></li>
                        <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur" target="_blank">THRISSUR</a></li>
                        <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode" target="_blank">CALICUT</a></li>
                        <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur" target="_blank">KANNUR</a></li>
                      </ul>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                      <a id="menu3" class="nav-link active text-white" aria-current="page" href="{% url 'booking' %}">BOOKING</a>
                </li>
                {% endif %}
                <li class="nav-item">
                      <a id="menu4" class="nav-link active text-white" aria-current="page" href="{% url 'departments' %}">DEPARTMENTS</a>
                </li>

              </ul><hr>

              <div>
                      {% if user.is_authenticated %}

                          <li id="username" class="nav-item active nav-link navbar-nav text-white">Welcome {{user.username}}</li>
                          <a id="logout" type="button" class="btn btn-dark" href="/credentials/logout">LOGOUT <span class="sr-only">(current)</span></a>


                        {% else %}
                          <li style="list-style:none" class="nav-item active nav-link navbar-nav">
                              <a style="margin-left:0.625rem;line-spacing:0.625rem;" id="register" type="button" class="btn btn-dark" href="/credentials/register">REGISTER<span class="sr-only">(current)</span></a>
                              <a style="margin-left:0.625rem;line-spacing:0.625rem;" id="login" type="button" class="btn btn-dark" href="/credentials/login">LOGIN<span class="sr-only">(current)</span></a>
                          </li>
                        {% endif %}
<!--                  <a id="login" type="button" class="btn btn-dark" href="/credentials/login">LOGIN</a>-->
<!--                  <a id="register" type="button" class="btn btn-dark" href="/credentials/register">REGISTER</a>-->
<!--                  <a id="logout" type="button" class="btn btn-dark" href="/credentials/logout">LOGOUT</a>-->
              </div>

          </div>
          </div>
    </nav>

    <section class="fixed-bottom">
      <footer class="pt-1 pb-1  bg-primary text-light">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12 col-md-8">
              <h6>Emergency Contact Number: 0123456789</h6>
            </div>
            <div class="col-12 col-md-4 mt-4 mt-md-0 text-center text-md-end">
              © 2023 City Bank. All Rights Reserved
            </div>
          </div>
        </div>
      </footer>
    </section>

    {% block content %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>


  </body>

</html>

bankproject/templates/booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%}
Booking
{% endblock %}

{% block content%}
<h1 class="text-center">Make An Appointment</h1>
<hr>
<!--<div class="container w-50 text-center p-3 my-5 bg-info">-->
<!--    <form action="" method="POST">-->
<!--        {% csrf_token %}-->
<!--        {{form|crispy}}-->
<!--        <br>-->
<!--        <button class="btn btn-primary mb-4" type="submit">Submit</button>-->

<!--    </form>-->
<!--</div>-->

<form class="container w-50 text-center p-3 my-5 bg-info" method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>
{% endblock %}

bankproject/templates/branches.html
{% extends 'base.html' %}
{% block title %}
Branches
{% endblock %}
{% block content %}
<h1>Our Branches</h1>
{% endblock %}

bankproject/templates/confirmation.html
{% extends 'base.html' %}

{% block title%}
Booking Confirmation
{% endblock %}

{% block content%}
<div class="container text-center">
    <h1>Booking Confirmation</h1>

    <div class="alert alert-info" role="alert">
        We have received your appointment request, our representative will call you shortly.<br>
        <a href="{% url 'home' %}">Back to home</a>
    </div>
</div>
{% endblock %}

bankproject/templates/departments.html
{% extends "base.html" %}
{% block title %}
Department
{% endblock %}
{% block content %}
<div class="text-center">
    <h1>Our Departments</h1>
</div>
<hr>
{% for d in dept%}
<div class="container">
<div class="mx-auto bg-primary text-center text-white p-3 my-5 border border-warning rounded ">
    <h1>{{d.dep_name}}</h1>
    <p>{{d.dep_description}}</p>
</div>
</div>

{% endfor %}

{% endblock %}

bankproject/templates/doctors.html
{% extends 'base.html' %}
{% block title %}
Doctors
{% endblock %}
{% block content %}
<h1>Doctors Page</h1>
{% endblock %}

bankproject/templates/dropdown.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

bankproject/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
{% load static %}
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel"
     xmlns="http://www.w3.org/1999/html">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="{% static '/imgs/1.png'%}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="{% static '/imgs/2.png'%}" class="d-block w-100" alt="...">

      </div>
      <div class="carousel-item">
        <img src="{% static '/imgs/4.png'%}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>




  <!-- service section -->

<main>
  <section class="service_section">
    <div class="container col-sm-6 col-md-6 col-xs-12">
      <div class="heading_container heading_center">
        <h2 style="font-weight:bold;font-size:2.9rem; bold;margin-top:70px;" class="text-center">
          OUR SERVICES
        </h2>
      </div>
    </div>

<div class="container-fluid">
    <div class="container-fluid">
            <div id="section2" class="row g-0 md-flex" style="margin-top:2.375rem;padding:0;">

                <div id="image2bg" class="col-sm-6 col-md-6 col-xs-12  " style="background-color:#7A948E;">
                    <h4 id="image2-heading" style="text-align:center;margin-top:28px;font-family: SoDoSans,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;font-size:2.8rem;"> LOW INTEREST LOAN FACILITIES<br> & 0% HOME LOAN</h4>
                    <p id="image2-para" style="text-align:center;margin-top:1.8125rem;font-size:1.3rem;font-family: SoDoSans,Helvetica Neue,Helvetica,Arial,sans-serif;"> City bank provides loans with low interests rate and home loans with 0% intrest.Moreover,We offer free and straightforward services without any hidden fees or charges on our part. And as we care about your comfort and safety, we enable you to submit a request without having to worry about any obligations or threats to your data security. </p>
                </div>
                <div id="image2" class="col-sm-6 col-md-6 col-xs-12  img-fluid" style="display:flex;">
                     <img src="{% static '/imgs/9.png'%}" class="img-fluid" alt="Responsive image" >
                 </div>
            </div>

    </div>

    <div class="container-fluid">
     <div class="row g-0 md-flex" style="margin-top:20px">
       <div  class="col-sm-6 col-md-6 col-xs-12" style="margin-top:1px;background-color:#d4e9e2;display:flex;">
         <img src="{% static '/imgs/6.png'%}" class="img-fluid" alt="Responsive image" >
       </div>
       <div  style="margin-top:1px;background-color:#CFC8A3;" class="col-sm-6 col-md-6 col-xs-12">
         <h4 style="text-align:center;margin-top:28px; font-family: SoDoSans,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;font-size:2rem;"> ONE TAP TRANSACTIONS </h4>
         <p style="text-align:center;margin-top:1.8125rem;font-size:1.3rem;font-family: SoDoSans,Helvetica Neue,Helvetica,Arial,sans-serif;"> City Bank offers a selection of cards to perfectly complement your distinct lifestyle needs.Apply online for Debit cards,Credit cards,Prepaid cards, Commercial cards and more. </p>
       </div>
       </div>
   </div>


    <div class="container-fluid">
            <div class="row g-0 md-flex" style="margin-top:2.375rem;padding:0;">

                <div  class="col-sm-6 col-md-6 col-xs-12  " style="background-color:#1C95B4;">
                    <h4  style="text-align:center;margin-top:28px;font-family: SoDoSans,Helvetica Neue,Helvetica,Arial,sans-serif;font-weight:bold;font-size:2.8rem;"> BEST INVESTMENT PLANS </h4>
                    <p style="text-align:center;margin-top:1.8125rem;font-size:1.3rem;font-family: SoDoSans,Helvetica Neue,Helvetica,Arial,sans-serif;"> Every individual has specific needs and priorities.<br> Your needs could vary from buying a house, providing for your child’s education, getting your child married, retirement and many more.<br> City Bank's investment services cater your all financial needs and help secure your future.  </p>
                </div>
                <div  class="col-sm-6 col-md-6 col-xs-12  img-fluid" style="display:flex;">
                     <img src="{% static '/imgs/8.png'%}" class="img-fluid" alt="Responsive image" >
                 </div>
            </div>

    </div>
  </div>

  </section>

  <section  class="about">
    <div class="container col-sm-6 col-md-6 col-xs-12">
      <div class="heading_container heading_center">
        <h2 style="font-weight: bold;margin-top:70px;" class="text-center">
          ABOUT US
        </h2>
      </div>
    </div>
    <div class="container-fluid col-sm-10 col-md-10col-xs-12">
        <p style="font-weight: normal;margin-top:70px;" >
          City Bank was formed in 1975 at the initiative of the World Bank, the Government of India and representatives of Indian industry.
          The principal objective was to create a development financial institution for providing medium-term and long-term project financing
            to Indian businesses. Until the late 1990s, City bank primarily focused its activities on project finance, providing long-term funds
            to a variety of industrial projects.Along with its subsidiaries and other group companies, offered a wide variety of products and
            services. As India’s economy became more market-oriented and integrated with the world economy,City bank capitalized on the new
            opportunities to provide a wider range of financial products and services to a broader spectrum of clients.
          The issue of universal banking, which in the Indian context meant conversion of long-term lending institutions such as City bank into
            commercial banks, had been discussed at length in the late 1990s. Conversion into a bank offered City bank the ability to accept low-cost
            demand deposits and offer a wider range of products and services, and greater opportunities for earning non-fund based income in the
            form of banking fees and commissions.The merger would enhance value for City bank shareholders through the merged entity's access to
            low-cost deposits, greater opportunities for earning fee-based income and the ability to participate in the payments system and provide
            transaction-banking services. The merger would enhance value for City Bank shareholders through a large capital base and scale of
            operations, seamless access to City bank's strong corporate relationships built up over five decades, entry into new business segments,
            higher market share in various business segments, particularly fee-based services, and access to the vast talent pool of City bank and
            its subsidiaries.
        </p>
    </div>
  </section>

</main>

<br>
<br>
<br>

{% endblock %}

bankproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
LOGIN
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form class="container w-50 text-center p-5 my-6 bg-info" action="" method="POST">
  {% csrf_token %}
    <div>
        <input style="width:70%;margin-top: 8px;padding:8px;border-radius:0.5px;" type="text" name="username" placeholder="Enter your username"><br>
        <input style="width:70%;margin-top:16px;padding:8px;border-radius:0.5px;" type="password" name="password" placeholder="Enter your password"><br>
    </div>
    <input class="btn btn-primary mb-4" style="width:70%;margin-top:22px;padding:3px;"  type="submit">
</form>
</body>
</html>
{% endblock %}

bankproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<h2 style="text-align:center;">REGISTER HERE</h2>
<form class="container w-50 text-center p-5 my-6 bg-info" action="" method="POST">
    {% csrf_token %}
    <div>
    <input style="width:70%;margin-top: 8px;padding:8px;border-radius:0.5px;" type="text" name="username" placeholder="Enter your username"><br>
    <input style="width:70%;margin-top: 8px;padding:8px;border-radius:0.5px;" type="password" name="password" placeholder="Enter your password"><br>
    <input style="width:70%;margin-top: 8px;padding:8px;border-radius:0.5px;" type="password" name="password1" placeholder="Confirm your password"><br>
    </div>
    <input class="btn btn-primary mb-4" style="width:70%;margin-top:22px;padding:3px;" type="submit">
</form>

</body>
</html>
{% endblock %}